# -*- coding: utf-8 -*-
"""for_loop_assignments

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnJRz7psJO6LtTuO3Bhi-gZbLkfgC2Fp
"""

#1 count how vowels are in a given string
#define vowels
vowels = "aeiouAEIOU" #both upper and lower case
#initialize the count
count = 0
#string from input
string = input("Enter the string: ")
#iterate through each character in the string
for char in string:
  #check if character is a vowel
  if char in vowels:
    #increment the count
    count += 1
#print the count
print("Number of vowels in the string:", count)

#2 program that prints the multiplication table of a given number using a "for loop"
#user input for the number
number = int(input("Enter a number: "))
#print table
print(f"\nMultiplication table for {number}:")
for i in range(1, 11): #loop through 1 to 11
  print(f"{number} x {i} = {number * i}")

#3 program that uses a for loop to iterate over a dictionary and print each key-value pair
#sample dictionary
student_grades = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "Diana": 88,
    "Eve": 91
}
for student, grade in student_grades.items():
  print(f"\n{student}: {grade}")

#4 program that takes a list of integers and uses a for loop to count how many numbers are even
#and how many are odd
#list of integers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#initialize counters
even_count = 0
odd_count = 0
#create list variables to store even and odd numbers
even_numbers = []
odd_numbers = []
#loop through list of numbers
for number in numbers:
  #check if number is even
  if number % 2 == 0:
    #increment even counter
    even_count += 1
    #add even number to list
    even_numbers.append(number)
  else: #the number is odd
    #increment odd counter
    odd_count += 1
    #add odd number to list
    odd_numbers.append(number)

#print even count and numbers
print(f"\nNumber of even numbers: {even_count}")
print(f"Even numbers: {even_numbers}")
#print odd count and numbers
print(f"\nNumber of odd numbers: {odd_count}")
print(f"Odd numbers: {odd_numbers}")

#5 program that takes a list of numbers and uses a for loop to find the largest and smallest number without using
#the built-in max() and min() functions
#sample list
numbers = [3,5,7,2,8,-1,4]
#initialize variables to sstore the largest and smallest numbers
largest = 0
smallest = 0
#start by assuming the first number is both the largest and smallest
#use for loop to iterate through the list
for number in numbers:
  #if the current number is greater than the largest, we update largest
  if number > largest:
    largest = number
  #if the current number is less than the smallest, we update smallest
  elif number < smallest:
    smallest = number
    #after loop is finished, the variables hold the largest and smallest values from the list
#print the largest and smallest numbers
print(f"\nLargest number: {largest}")
print(f"Smallest number: {smallest}")