# -*- coding: utf-8 -*-
"""for_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUwAo-I6WsEQEsXwgLj8XXIWO7j-TZDG
"""

# Square list of elements
numbers = [2, 4, 6, 8]
for i in range(len(numbers)):
    numbers[i] = numbers[i] * numbers[i]
print(numbers)

# Grade Calculator
marks = [85, 92, 78, 90, 88]
#declare total variable
total = 0
#for loop to calculate average mark
for mark in marks:
    total += mark
average = total / len(marks)
#print the average mark
print("Average mark:", average)
#based on the average mark print correspinding grade
if 90 <= average <= 100:
    print("Grade: A")
elif 80 <= average < 90:
    print("Grade: B")
elif 70 <= average < 80:
    print("Grade: C")
elif 60 <= average < 70:
    print("Grade: D")
else:
    print("Grade: F")