# -*- coding: utf-8 -*-
"""four_digit_while_loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLAvuGksw9C2dHDBLoTnNOAC7Zzbi2r6
"""

# four digits with while loop

def four_digit_num():
  while True:
    #input: enter a four-digit number
    digits = int(input("Enter a 4 digit number: "))
    #check if input is 4 digits
    if 1000 <= digits <= 9999:
      #processing: extract the digits
      digit1 = digits // 1000
      digit2 = (digits % 1000) // 100
      digit3 = (digits % 100) // 10
      digit4 = digits % 10

      #output: display individual digits and their sum
      print(f"The individual digits are {digit1}, {digit2}, {digit3}, and {digit4}.")
      print(f"The sum of the digits is {digit1 + digit2 + digit3 + digit4}.")
      break #exit loop
    else:
      print("Your input was not 4 digits, please try again.")
      continue #continue loop

four_digit_num()